//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Of_Phone_seller_PROJECT {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlFiles() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARM_Of_Phone_seller_PROJECT.SqlFiles", typeof(SqlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на use ARM_Of_Phone_Seller
        ///go
        ///INSERT INTO Специалист VALUES (N&apos;admin&apos;, N&apos;21232F297A57A5A743894A0E4A801FC3&apos;, 375290001122, N&apos;Главная учетная запись администратора&apos;, N&apos;Админ&apos;, N&apos;Админ&apos;, N&apos;Админ&apos;, &apos;2000-01-01&apos;, N&apos;Главная учетная запись администратора&apos;, &apos;true&apos;).
        /// </summary>
        public static string SQL_AddAdmin {
            get {
                return ResourceManager.GetString("SQL_AddAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USE [master]
        ///GO
        ////****** Object:  Database [ARM_Of_Phone_Seller]    Script Date: 17.12.2019 15:00:45 ******/
        ///CREATE DATABASE [ARM_Of_Phone_Seller]
        /// CONTAINMENT = NONE
        /// ON  PRIMARY 
        ///( NAME = N&apos;ARM_Of_Phone_Seller&apos;, FILENAME = N&apos;D:\Репозитории\ARM_Of_Phone_seller\ARM_Of_Phone_Seller.mdf&apos; , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
        /// LOG ON 
        ///( NAME = N&apos;ARM_Of_Phone_Seller_log&apos;, FILENAME = N&apos;D:\Репозитории\ARM_Of_Phone_seller\ARM_Of_Phone_Seller_log.ldf&apos; , SIZE = 8192KB , MAXSIZE = 2048G [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string SQL_DB_Creation {
            get {
                return ResourceManager.GetString("SQL_DB_Creation", resourceCulture);
            }
        }
    }
}
